
# This file is part of p4est.
# Makefile.am in example/v3basics
# included non-recursively from toplevel directory

if P4EST_ENABLE_BUILD_2D
bin_PROGRAMS += example/v3basics/p4est3_basics
example_v3basics_p4est3_basics_SOURCES = example/v3basics/basics2.c

LINT_CSOURCES += $(example_v3basics_p4est3_basics_SOURCES)
endif

## if P4EST_ENABLE_BUILD_3D
## bin_PROGRAMS += example/v3basics/p8est3_basics
## 
## example_v3basics_p8est3_basics_SOURCES = example/v3basics/basics3.c
## 
## LINT_CSOURCES += $(example_v3basics_p8est3_basics_SOURCES)
## endif
